version: '3.8'
services:
  db:
    container_name: db
    image: bitnami/mysql:8.1.0
    volumes:
      - mysql_data:/bitnami/mysql/data
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - pbwl
    ports:
      - 6033:3306
networks:
  pbwl:
    driver: bridge
volumes:
  mysql_data:
    driver: local